{{- if and (eq (include "min.keycloakEnabled" .) "true") .Values.keycloak.customCert.crt }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "min.keycloak.serviceName" . }}-custom-cert
  labels:
    {{- include "min.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
type: Opaque
stringData:
  {{ .Values.keycloak.customCert.fileName | quote }}: |
{{ .Values.keycloak.customCert.crt | nindent 4 }}
{{- end }}
