{{- if and (eq (include "min.keycloakEnabled" .) "true") .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "min.keycloak.postgresqlName" . }}-auth
  labels:
    {{- include "min.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
type: Opaque
stringData:
  database: {{ .Values.postgresql.auth.database | quote }}
  username: {{ .Values.postgresql.auth.username | quote }}
  password: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
