{{- if eq (include "min.keycloakEnabled" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "min.keycloak.serviceName" . }}
  labels:
    {{- include "min.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - name: http
      port: {{ .Values.keycloak.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "min.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
{{- end }}
