{{- if and (eq (include "min.keycloakEnabled" .) "true") .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "min.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "min.labels" . | nindent 4 }}
{{- end }}
