// kubernetes-opa.bicep
// Radius Recipe: Radius.Resources/governance
//
// Deploys Open Policy Agent (OPA) with the embedded Envoy External Authorization
// gRPC plugin as a centralized policy decision point (PDP) in the application
// namespace. The output `decisionEndpoint` ("<service>:<port>") is suitable for
// registration as an Istio extensionProvider of kind `envoyExtAuthzGrpc` so
// AuthorizationPolicy resources with `action: CUSTOM` can delegate decisions
// to this PDP.
//
// Optionally (when `istioIntegration=true`) the recipe also runs a Kubernetes
// Job that patches the Istio MeshConfig ConfigMap to register the PDP as an
// `extensionProvider` and restarts istiod so the new MeshConfig is propagated
// to all sidecars. This makes the recipe a drop-in replacement for the OPA +
// post-install hook installed by the `ent` Helm portfolio.
//
// MIGRATION NOTE
//   This recipe is the portable equivalent of:
//     - charts/portfolios/ent/templates/opa.yaml                       (PDP workload)
//     - charts/portfolios/ent/templates/post-install-istio-extauthz.yaml (mesh wiring)
//   When migrating, set `ent.opa.enabled=false` and `ent.istioExtAuthz.enabled=false`
//   in the Helm values, deploy this recipe with `istioIntegration=true`, and
//   AuthorizationPolicy resources can continue to use the same provider name
//   (default `opa-ext-authz-grpc`).

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Enforcement mode hint passed by the resource. Reserved for future use; currently informational only.')
@allowed([
  'enforce'
  'audit'
  'dryrun'
])
param mode string = 'enforce'

@description('Inline Rego policy bundle loaded by OPA. When empty, a default-allow policy is loaded so the data plane remains functional out of the box.')
param policy string = ''

@description('Rego decision path consulted by the Envoy ext_authz plugin for each request.')
param decisionPath string = '/envoy/authz/allow'

@description('opa-envoy-plugin container image. The `-envoy` tag suffix includes the embedded Envoy ext_authz gRPC plugin.')
param image string = 'openpolicyagent/opa:1.10.0-envoy'

@description('Number of OPA replicas.')
param replicas int = 1

@description('gRPC port served by the Envoy ext_authz plugin.')
param grpcPort int = 9191

@description('OPA management REST API port (policy upload, data API).')
param httpPort int = 8181

@description('Diagnostic endpoint port used for liveness/readiness probes.')
param diagnosticPort int = 8282

@description('OPA log level (debug, info, warn, error).')
param logLevel string = 'info'

@description('When true, run a post-install Job that registers this PDP as an Istio extensionProvider (envoyExtAuthzGrpc) by patching the Istio MeshConfig ConfigMap and restarting istiod. Requires Istio to be installed in the cluster.')
param istioIntegration bool = false

@description('Namespace where the Istio control plane (and its MeshConfig ConfigMap) lives.')
param istioNamespace string = 'istio-system'

@description('Name of the ConfigMap holding the Istio MeshConfig.')
param istioConfigMap string = 'istio'

@description('Name registered for the extensionProvider. AuthorizationPolicy resources reference this name via `provider.name`.')
param istioProviderName string = 'opa-ext-authz-grpc'

@description('Image used by the post-install Istio-patching Job. Must include `kubectl`, `jq`, and `apk`/`yq`.')
param istioPatchImage string = 'dtzar/helm-kubectl:3.17'

var resourceBaseName = toLower(replace(context.resource.name, '_', '-'))
var opaName = '${resourceBaseName}-opa'
var namespace = context.runtime.kubernetes.namespace
var applicationName = context.application == null ? '' : context.application.name

var commonLabels = {
  app: 'opa'
  resource: context.resource.name
  'radapp.io/application': applicationName
  'app.kubernetes.io/component': 'governance'
  'app.kubernetes.io/managed-by': 'radius'
}

// Default-allow policy applied when the caller does not supply one. Mirrors
// the default in charts/portfolios/ent/templates/opa.yaml.
var defaultPolicyRego = '''package envoy.authz

import rego.v1

# Default-allow policy. Replace with workload-specific rules.
default allow := true
'''

var effectivePolicy = policy == '' ? defaultPolicyRego : policy

// OPA runtime configuration. The plugins block enables the embedded
// envoy.ext_authz gRPC server on the configured port. Built with string
// interpolation because Bicep multi-line strings ('''...''') are verbatim
// and do not expand `${...}` expressions.
var opaConfigYaml = 'decision_logs:\n  console: true\nplugins:\n  envoy_ext_authz_grpc:\n    addr: :${grpcPort}\n    path: ${decisionPath}\n'

extension kubernetes with {
  kubeConfig: ''
  namespace: namespace
} as kubernetes

// ------------------------------------------------------------------
// ServiceAccount
// ------------------------------------------------------------------
resource opaServiceAccount 'core/ServiceAccount@v1' = {
  metadata: {
    name: opaName
    namespace: namespace
    labels: commonLabels
  }
}

// ------------------------------------------------------------------
// ConfigMap — OPA runtime config
// ------------------------------------------------------------------
resource opaConfig 'core/ConfigMap@v1' = {
  metadata: {
    name: '${opaName}-config'
    namespace: namespace
    labels: commonLabels
  }
  data: {
    'config.yaml': opaConfigYaml
  }
}

// ------------------------------------------------------------------
// ConfigMap — Rego policy bundle
// ------------------------------------------------------------------
resource opaPolicy 'core/ConfigMap@v1' = {
  metadata: {
    name: '${opaName}-policy'
    namespace: namespace
    labels: commonLabels
  }
  data: {
    'policy.rego': effectivePolicy
  }
}

// ------------------------------------------------------------------
// Deployment
// ------------------------------------------------------------------
resource opaDeployment 'apps/Deployment@v1' = {
  metadata: {
    name: opaName
    namespace: namespace
    labels: commonLabels
    annotations: {
      'radapp.io/governance-mode': mode
    }
  }
  spec: {
    replicas: replicas
    selector: {
      matchLabels: {
        app: 'opa'
        resource: context.resource.name
      }
    }
    template: {
      metadata: {
        labels: commonLabels
        annotations: {
          // OPA is the PDP for the mesh; it must not be subject to its own
          // enforcement. Skip Istio sidecar injection.
          'sidecar.istio.io/inject': 'false'
        }
      }
      spec: {
        serviceAccountName: opaName
        containers: [
          {
            name: 'opa'
            image: image
            imagePullPolicy: 'IfNotPresent'
            args: [
              'run'
              '--server'
              '--addr=0.0.0.0:${httpPort}'
              '--diagnostic-addr=0.0.0.0:${diagnosticPort}'
              '--config-file=/config/config.yaml'
              '--log-level=${logLevel}'
              // ConfigMap volume mounts expose hidden ..data symlinks pointing
              // to timestamped directories; without this OPA loads policy.rego
              // multiple times and fails with "multiple default rules".
              '--ignore=.*'
              '/policies'
            ]
            ports: [
              {
                name: 'grpc'
                containerPort: grpcPort
                protocol: 'TCP'
              }
              {
                name: 'http'
                containerPort: httpPort
                protocol: 'TCP'
              }
              {
                name: 'diagnostic'
                containerPort: diagnosticPort
                protocol: 'TCP'
              }
            ]
            readinessProbe: {
              httpGet: {
                path: '/health?plugins'
                port: 'diagnostic'
              }
              initialDelaySeconds: 5
              periodSeconds: 10
            }
            livenessProbe: {
              httpGet: {
                path: '/health'
                port: 'diagnostic'
              }
              initialDelaySeconds: 10
              periodSeconds: 20
            }
            volumeMounts: [
              {
                name: 'config'
                mountPath: '/config'
                readOnly: true
              }
              {
                name: 'policies'
                mountPath: '/policies'
                readOnly: true
              }
            ]
            resources: {
              requests: {
                cpu: '50m'
                memory: '128Mi'
              }
              limits: {
                cpu: '500m'
                memory: '512Mi'
              }
            }
          }
        ]
        volumes: [
          {
            name: 'config'
            configMap: {
              name: opaConfig.metadata.name
            }
          }
          {
            name: 'policies'
            configMap: {
              name: opaPolicy.metadata.name
            }
          }
        ]
      }
    }
  }
}

// ------------------------------------------------------------------
// Service
// ------------------------------------------------------------------
resource opaService 'core/Service@v1' = {
  metadata: {
    name: opaName
    namespace: namespace
    labels: commonLabels
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      app: 'opa'
      resource: context.resource.name
    }
    ports: [
      {
        name: 'grpc'
        port: grpcPort
        targetPort: 'grpc'
        protocol: 'TCP'
        appProtocol: 'grpc'
      }
      {
        name: 'http'
        port: httpPort
        targetPort: 'http'
        protocol: 'TCP'
      }
    ]
  }
}

var decisionServiceDns = '${opaService.metadata.name}.${namespace}.svc.cluster.local'

// ------------------------------------------------------------------
// Optional Istio integration — patch MeshConfig.extensionProviders.
// Mirrors charts/portfolios/ent/templates/post-install-istio-extauthz.yaml.
// All four resources are guarded by `istioIntegration` and only
// referenced in `output.resources` when present (avoids conditional
// dependsOn pitfalls).
// ------------------------------------------------------------------
var istioJobBaseName = '${opaName}-istio-extauthz'

// Cluster-scoped names must be globally unique — qualify with namespace.
var clusterScopedName = '${namespace}-${istioJobBaseName}'

resource istioPatchServiceAccount 'core/ServiceAccount@v1' = if (istioIntegration) {
  metadata: {
    name: istioJobBaseName
    namespace: namespace
    labels: commonLabels
  }
}

resource istioPatchClusterRole 'rbac.authorization.k8s.io/ClusterRole@v1' = if (istioIntegration) {
  metadata: {
    name: clusterScopedName
    labels: commonLabels
  }
  rules: [
    {
      apiGroups: ['']
      resources: ['configmaps']
      verbs: ['get', 'update', 'patch', 'list']
    }
    {
      apiGroups: ['apps']
      resources: ['deployments']
      verbs: ['get', 'patch', 'list']
    }
  ]
}

resource istioPatchClusterRoleBinding 'rbac.authorization.k8s.io/ClusterRoleBinding@v1' = if (istioIntegration) {
  metadata: {
    name: clusterScopedName
    labels: commonLabels
  }
  roleRef: {
    apiGroup: 'rbac.authorization.k8s.io'
    kind: 'ClusterRole'
    name: clusterScopedName
  }
  subjects: [
    {
      kind: 'ServiceAccount'
      name: istioJobBaseName
      namespace: namespace
    }
  ]
}

// Shell script is held in a triple-quoted Bicep string (verbatim, no
// interpolation). All Bicep-provided values are passed via container env vars
// (ISTIO_NS, ISTIO_CM, PROVIDER_NAME, OPA_SERVICE, OPA_PORT).
var istioPatchScript = '''set -euo pipefail

echo "Waiting for istio ConfigMap ${ISTIO_CM} in ${ISTIO_NS}..."
until kubectl -n "${ISTIO_NS}" get configmap "${ISTIO_CM}" >/dev/null 2>&1; do
  sleep 3
done

# Install yq (mikefarah, Go binary) for deterministic YAML editing.
# jq is already present in dtzar/helm-kubectl.
if ! command -v yq >/dev/null 2>&1; then
  apk add --no-cache yq >/dev/null
fi

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# Pull current MeshConfig (the value of data.mesh); default to {}.
kubectl -n "${ISTIO_NS}" get configmap "${ISTIO_CM}" \
  -o jsonpath='{.data.mesh}' > "$TMP/mesh.yaml" || true
if [ ! -s "$TMP/mesh.yaml" ]; then
  echo "{}" > "$TMP/mesh.yaml"
fi

# Remove any pre-existing entry with our provider name, then append
# a fresh one.
export PROVIDER_NAME OPA_SERVICE OPA_PORT
yq -i '
  .extensionProviders = ((.extensionProviders // [])
    | map(select(.name != strenv(PROVIDER_NAME))))
    + [{
        "name": strenv(PROVIDER_NAME),
        "envoyExtAuthzGrpc": {
          "service": strenv(OPA_SERVICE),
          "port": (env(OPA_PORT) | tonumber)
        }
      }]
' "$TMP/mesh.yaml"

echo "Updated MeshConfig:"
cat "$TMP/mesh.yaml"

# Patch the ConfigMap's data.mesh field with the rendered YAML.
PATCH=$(jq -Rs '{data: {mesh: .}}' < "$TMP/mesh.yaml")
kubectl -n "${ISTIO_NS}" patch configmap "${ISTIO_CM}" \
  --type merge -p "$PATCH"

# Restart istiod so the new MeshConfig is reloaded and pushed to sidecars.
# Tolerate absence (AKS Istio add-on) — the add-on reconciles user
# customizations from this ConfigMap on its own.
if kubectl -n "${ISTIO_NS}" get deployment istiod >/dev/null 2>&1; then
  echo "Restarting istiod to pick up new MeshConfig..."
  kubectl -n "${ISTIO_NS}" rollout restart deployment/istiod
  kubectl -n "${ISTIO_NS}" rollout status deployment/istiod --timeout=180s
else
  echo "istiod deployment not found in ${ISTIO_NS}; assuming managed control plane will reconcile."
fi

echo "Registered Istio extensionProvider '${PROVIDER_NAME}' -> ${OPA_SERVICE}:${OPA_PORT}."
'''

resource istioPatchJob 'batch/Job@v1' = if (istioIntegration) {
  metadata: {
    name: istioJobBaseName
    namespace: namespace
    labels: commonLabels
  }
  spec: {
    backoffLimit: 1
    // Keep the pod (and its logs) around for a while after the Job finishes
    // so failures can be debugged with `kubectl logs`.
    ttlSecondsAfterFinished: 600
    template: {
      metadata: {
        labels: commonLabels
        annotations: {
          // Don't subject the patcher to mesh enforcement during its own
          // bootstrap.
          'sidecar.istio.io/inject': 'false'
        }
      }
      spec: {
        serviceAccountName: istioJobBaseName
        restartPolicy: 'OnFailure'
        containers: [
          {
            name: 'patch-istio'
            image: istioPatchImage
            env: [
              {
                name: 'ISTIO_NS'
                value: istioNamespace
              }
              {
                name: 'ISTIO_CM'
                value: istioConfigMap
              }
              {
                name: 'PROVIDER_NAME'
                value: istioProviderName
              }
              {
                name: 'OPA_SERVICE'
                value: decisionServiceDns
              }
              {
                name: 'OPA_PORT'
                value: '${grpcPort}'
              }
            ]
            command: [
              '/bin/sh'
              '-c'
              istioPatchScript
            ]
          }
        ]
      }
    }
  }
  // The Job depends on the RBAC being in place before it runs. The OPA
  // Service is referenced via `decisionServiceDns` (a value used in env),
  // which already gives Bicep an implicit dependency on opaService.
  dependsOn: [
    istioPatchClusterRoleBinding
  ]
}

var baseResources = [
  '/planes/kubernetes/local/namespaces/${namespace}/providers/core/ServiceAccount/${opaServiceAccount.metadata.name}'
  '/planes/kubernetes/local/namespaces/${namespace}/providers/core/ConfigMap/${opaConfig.metadata.name}'
  '/planes/kubernetes/local/namespaces/${namespace}/providers/core/ConfigMap/${opaPolicy.metadata.name}'
  '/planes/kubernetes/local/namespaces/${namespace}/providers/apps/Deployment/${opaDeployment.metadata.name}'
  '/planes/kubernetes/local/namespaces/${namespace}/providers/core/Service/${opaService.metadata.name}'
]

var istioIntegrationResources = istioIntegration ? [
  '/planes/kubernetes/local/namespaces/${namespace}/providers/core/ServiceAccount/${istioJobBaseName}'
  '/planes/kubernetes/local/providers/rbac.authorization.k8s.io/ClusterRole/${clusterScopedName}'
  '/planes/kubernetes/local/providers/rbac.authorization.k8s.io/ClusterRoleBinding/${clusterScopedName}'
  '/planes/kubernetes/local/namespaces/${namespace}/providers/batch/Job/${istioJobBaseName}'
] : []

output result object = {
  resources: concat(baseResources, istioIntegrationResources)
  values: {
    provider: 'opa'
    decisionService: decisionServiceDns
    decisionPort: grpcPort
    decisionEndpoint: '${decisionServiceDns}:${grpcPort}'
    decisionPath: decisionPath
    managementEndpoint: 'http://${decisionServiceDns}:${httpPort}'
    istioProviderName: istioIntegration ? istioProviderName : ''
  }
}
