// kubernetes-agt-sidecar.bicep
// Radius Recipe: Radius.Resources/agentGuardrails
//
// Stages the prerequisites for an in-pod *agent governance sidecar* (the
// Microsoft Agent Governance Toolkit "OpenClaw sidecar" pattern). Because the
// sidecar must live inside the agent's own pod, this recipe does NOT deploy a
// Deployment/Service for the sidecar itself; the application Bicep injects
// the sidecar container via `runtimes.kubernetes.pod` on the agent
// Applications.Core/containers resource.
//
// What the recipe DOES deploy:
//   • core/ConfigMap "<resource>-policies" — the policy bundle the sidecar
//     mounts at /policies. When `policies` is empty a default-allow
//     placeholder is written so the mount succeeds.
//
// What the recipe outputs (consumed by the application via parameter
// convention — see app.bicep; the application must NOT read these via
// resource property references because that creates a conditional dependency
// edge that crashes the Radius Deployment Engine in v0.57.x):
//   • provider              — "agt-openclaw-sidecar"
//   • policiesConfigMapName — name of the ConfigMap above
//   • sidecarImage          — recommended sidecar image
//   • proxyPort             — sidecar API/proxy port (8081)
//   • metricsPort           — sidecar metrics port (9091)
//   • policiesMountPath     — "/policies"
//
// SECURITY MODEL NOTE
//   The sidecar trusts that all callers reach it over `localhost`. This
//   recipe relies on the application Bicep to co-locate the sidecar in the
//   agent pod. Do NOT expose the sidecar as a Service or Gateway — that
//   defeats AGT's trust assumptions.

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Enforcement mode hint surfaced to the sidecar via the AGT_MODE env var. Recipes / sidecar code may interpret this differently (e.g. "audit" logs but never blocks).')
@allowed([
  'enforce'
  'audit'
  'dryrun'
])
param mode string = 'enforce'

@description('Inline policy bundle written to /policies/policies.yaml inside the sidecar. When empty, a default-allow placeholder is written so the ConfigMap exists and the agent pod can mount it.')
param policies string = ''

@description('Sidecar container image override. When empty, the recipe default below is used.')
param image string = ''

@description('Default sidecar image when the caller does not override `image`. Built from src/agt-sidecar/ in this repository and published by the build-and-publish workflow.')
param defaultImage string = 'ghcr.io/microsoft/adaptive-apps/agt-sidecar:latest'

@description('Sidecar log level (DEBUG, INFO, WARN, ERROR). Surfaced as the LOG_LEVEL env var by the application Bicep.')
param logLevel string = 'INFO'

@description('HTTP port the sidecar listens on for its governance proxy / API. Default 8081 matches the upstream AGT documentation.')
param proxyPort int = 8081

@description('HTTP port the sidecar exposes metrics on. Default 9091 matches the upstream AGT documentation.')
param metricsPort int = 9091

@description('Path inside the sidecar where the policies ConfigMap should be mounted.')
param policiesMountPath string = '/policies'

var resourceBaseName = toLower(replace(context.resource.name, '_', '-'))
var policiesConfigMapName = '${resourceBaseName}-policies'
var namespace = context.runtime.kubernetes.namespace
var applicationName = context.application == null ? '' : context.application.name

var commonLabels = {
  app: 'agt-sidecar'
  resource: context.resource.name
  'radapp.io/application': applicationName
  'app.kubernetes.io/component': 'agent-guardrails'
  'app.kubernetes.io/managed-by': 'radius'
}

// Default-allow placeholder. Mirrors the OPA recipe's pattern of keeping the
// data plane functional out of the box when the caller has not supplied a
// policy bundle yet. The exact schema interpreted by the AGT sidecar is
// still evolving upstream (see roadmap: "YAML policy loading from mounted
// volume"); this is a structurally valid YAML document the sidecar can
// parse and ignore until real rules are added.
var defaultPolicyYaml = '''# Default-allow placeholder written by the kubernetes-agt-sidecar Radius
# Recipe. Replace by setting the `policies` property on the
# Radius.Resources/agentGuardrails resource in your application Bicep.
policies: []
defaults:
  mode: enforce
  prompt_injection:
    sensitivity: balanced
'''

var effectivePolicies = policies == '' ? defaultPolicyYaml : policies
var effectiveImage = image == '' ? defaultImage : image

extension kubernetes with {
  kubeConfig: ''
  namespace: namespace
} as kubernetes

// ------------------------------------------------------------------
// ConfigMap — sidecar policy bundle
// ------------------------------------------------------------------
resource policiesConfigMap 'core/ConfigMap@v1' = {
  metadata: {
    name: policiesConfigMapName
    namespace: namespace
    labels: commonLabels
    annotations: {
      'radapp.io/agent-guardrails-mode': mode
    }
  }
  data: {
    'policies.yaml': effectivePolicies
  }
}

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${namespace}/providers/core/ConfigMap/${policiesConfigMap.metadata.name}'
  ]
  values: {
    provider: 'agt-openclaw-sidecar'
    policiesConfigMapName: policiesConfigMap.metadata.name
    sidecarImage: effectiveImage
    proxyPort: proxyPort
    metricsPort: metricsPort
    policiesMountPath: policiesMountPath
    logLevel: logLevel
    mode: mode
  }
}
