apiVersion: v2
name: core-ai
description: Core AI capability portfolio chart for Adaptive Apps. Builds on core.
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - adaptive-apps
  - capability-portfolio
  - core-ai
dependencies:
  - name: core
    version: 0.1.0
    repository: file://../core
home: https://github.com/microsoft/adaptive-apps
sources:
  - https://github.com/microsoft/adaptive-apps
maintainers:
  - name: adaptive-apps
