apiVersion: v2
name: min-ai
description: Min AI capability portfolio chart for Adaptive Apps. Builds on min.
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - adaptive-apps
  - capability-portfolio
  - min-ai
dependencies:
  - name: min
    version: 0.1.0
    repository: file://../min
home: https://github.com/microsoft/adaptive-apps
sources:
  - https://github.com/microsoft/adaptive-apps
maintainers:
  - name: adaptive-apps
