// kubernetes-keycloak.bicep
// Radius Recipe: Radius.Resources/identityProviders
//
// Deploys Keycloak on Kubernetes using a stateful setup with a dedicated
// PostgreSQL instance for exploratory/local environments.

@description('Information about what resource is calling this Recipe. Generated by Radius. For more information visit https://docs.radapp.io/reference/context-schema/')
param context object

@description('Keycloak container image.')
param keycloakImage string = 'quay.io/keycloak/keycloak:26.5.5'

@description('PostgreSQL container image.')
param postgresImage string = 'mirror.gcr.io/postgres:17'

@description('Number of Keycloak replicas. Use 2 for safer rolling updates.')
param replicas int = 2

@description('Bootstrap admin username for Keycloak.')
param adminUsername string = 'admin'

@description('Bootstrap admin password for Keycloak.')
@secure()
#disable-next-line secure-parameter-default
param adminPassword string = 'admin'

@description('Keycloak database name.')
param databaseName string = 'keycloak'

@description('Keycloak database username.')
param databaseUser string = 'keycloak'

@description('Keycloak database password.')
@secure()
#disable-next-line secure-parameter-default
param databasePassword string = 'keycloak'

@description('Optional public host for Keycloak ingress. Leave empty to use a deterministic localtest.me hostname.')
param keycloakPublicHost string = ''

var resourceBaseName = toLower(replace(context.resource.name, '_', '-'))
var keycloakName = '${resourceBaseName}-keycloak'
var keycloakDiscoveryName = '${keycloakName}-discovery'
var postgresName = '${resourceBaseName}-postgres'
var namespace = context.runtime.kubernetes.namespace
var effectiveKeycloakPublicHost = keycloakPublicHost == ''
	? '${keycloakName}.${namespace}.localtest.me'
	: keycloakPublicHost

extension kubernetes with {
	kubeConfig: ''
	namespace: namespace
} as kubernetes

// ------------------------------------------------------------------
// Keycloak Service
// ------------------------------------------------------------------
resource keycloakService 'core/Service@v1' = {
	metadata: {
		name: keycloakName
		namespace: namespace
		labels: {
			app: 'keycloak'
			resource: context.resource.name
			'radapp.io/application': context.application == null ? '' : context.application.name
		}
	}
	spec: {
		type: 'ClusterIP'
		selector: {
			app: 'keycloak'
			resource: context.resource.name
		}
		ports: [
			{
				protocol: 'TCP'
				port: 8080
				targetPort: 'http'
				name: 'http'
			}
		]
	}
}

// ------------------------------------------------------------------
// Headless discovery Service for Keycloak clustering
// ------------------------------------------------------------------
resource keycloakDiscoveryService 'core/Service@v1' = {
	metadata: {
		name: keycloakDiscoveryName
		namespace: namespace
		labels: {
			app: 'keycloak'
			resource: context.resource.name
			'radapp.io/application': context.application == null ? '' : context.application.name
		}
	}
	spec: {
		type: 'ClusterIP'
		clusterIP: 'None'
		selector: {
			app: 'keycloak'
			resource: context.resource.name
		}
	}
}

// ------------------------------------------------------------------
// Keycloak StatefulSet
// ------------------------------------------------------------------
resource keycloak 'apps/StatefulSet@v1' = {
	metadata: {
		name: keycloakName
		namespace: namespace
		labels: {
			app: 'keycloak'
			resource: context.resource.name
			'radapp.io/application': context.application == null ? '' : context.application.name
		}
	}
	spec: {
		serviceName: keycloakDiscoveryName
		replicas: replicas
		selector: {
			matchLabels: {
				app: 'keycloak'
				resource: context.resource.name
			}
		}
		template: {
			metadata: {
				labels: {
					app: 'keycloak'
					resource: context.resource.name
					'radapp.io/application': context.application == null ? '' : context.application.name
				}
			}
			spec: {
				containers: [
					{
						name: 'keycloak'
						image: keycloakImage
						args: [
							'start'
						]
						env: [
							{
								name: 'KC_BOOTSTRAP_ADMIN_USERNAME'
								value: adminUsername
							}
							{
								name: 'KC_BOOTSTRAP_ADMIN_PASSWORD'
								value: adminPassword
							}
							{
								name: 'KC_PROXY_HEADERS'
								value: 'xforwarded'
							}
							{
								name: 'KC_HTTP_ENABLED'
								value: 'true'
							}
							{
								name: 'KC_HOSTNAME'
								value: effectiveKeycloakPublicHost
							}
							{
								name: 'KC_HOSTNAME_STRICT'
								value: 'true'
							}
							{
								name: 'KC_HOSTNAME_STRICT_HTTPS'
								value: 'false'
							}
							{
								name: 'KC_HEALTH_ENABLED'
								value: 'true'
							}
							{
								name: 'KC_CACHE'
								value: 'ispn'
							}
							{
								name: 'POD_IP'
								valueFrom: {
									fieldRef: {
										fieldPath: 'status.podIP'
									}
								}
							}
							{
								name: 'KC_CACHE_EMBEDDED_NETWORK_BIND_ADDRESS'
								value: '$(POD_IP)'
							}
							{
								name: 'KC_DB_URL_DATABASE'
								value: databaseName
							}
							{
								name: 'KC_DB_URL_HOST'
								value: postgresName
							}
							{
								name: 'KC_DB'
								value: 'postgres'
							}
							{
								name: 'KC_DB_PASSWORD'
								value: databasePassword
							}
							{
								name: 'KC_DB_USERNAME'
								value: databaseUser
							}
						]
						ports: [
							{
								name: 'http'
								containerPort: 8080
							}
							{
								name: 'management'
								containerPort: 9000
							}
							{
								name: 'jgroups'
								containerPort: 7800
							}
							{
								name: 'jgroups-fd'
								containerPort: 57800
							}
						]
						startupProbe: {
							httpGet: {
								path: '/health/started'
								port: 'management'
							}
							periodSeconds: 1
							failureThreshold: 600
						}
						readinessProbe: {
							httpGet: {
								path: '/health/ready'
								port: 'management'
							}
							periodSeconds: 10
							failureThreshold: 3
						}
						livenessProbe: {
							httpGet: {
								path: '/health/live'
								port: 'management'
							}
							periodSeconds: 10
							failureThreshold: 3
						}
						resources: {
							limits: {
								cpu: '2000m'
								memory: '2000Mi'
							}
							requests: {
								cpu: '500m'
								memory: '1700Mi'
							}
						}
					}
				]
			}
		}
	}
}

// ------------------------------------------------------------------
// Public Ingress for Keycloak browser flows (k3s Traefik default class).
// ------------------------------------------------------------------
resource keycloakIngress 'networking.k8s.io/Ingress@v1' = {
	metadata: {
		name: '${keycloakName}-ingress'
		namespace: namespace
		labels: {
			app: 'keycloak'
			resource: context.resource.name
			'radapp.io/application': context.application == null ? '' : context.application.name
		}
		annotations: {
			'traefik.ingress.kubernetes.io/router.entrypoints': 'web'
		}
	}
	spec: {
		ingressClassName: 'traefik'
		rules: [
			{
				host: effectiveKeycloakPublicHost
				http: {
					paths: [
						{
							path: '/'
							pathType: 'Prefix'
							backend: {
								service: {
									name: keycloakName
									port: {
										number: 8080
									}
								}
							}
						}
					]
				}
			}
		]
	}
}

// ------------------------------------------------------------------
// PostgreSQL Deployment (ephemeral storage)
// ------------------------------------------------------------------
resource postgres 'apps/Deployment@v1' = {
	metadata: {
		name: postgresName
		namespace: namespace
		labels: {
			app: 'postgres'
			resource: context.resource.name
			'radapp.io/application': context.application == null ? '' : context.application.name
		}
	}
	spec: {
		replicas: 1
		selector: {
			matchLabels: {
				app: 'postgres'
				resource: context.resource.name
			}
		}
		template: {
			metadata: {
				labels: {
					app: 'postgres'
					resource: context.resource.name
					'radapp.io/application': context.application == null ? '' : context.application.name
				}
			}
			spec: {
				containers: [
					{
						name: 'postgres'
						image: postgresImage
						env: [
							{
								name: 'POSTGRES_USER'
								value: databaseUser
							}
							{
								name: 'POSTGRES_PASSWORD'
								value: databasePassword
							}
							{
								name: 'POSTGRES_DB'
								value: databaseName
							}
							{
								name: 'POSTGRES_LOG_STATEMENT'
								value: 'all'
							}
						]
						ports: [
							{
								name: 'postgres'
								containerPort: 5432
							}
						]
						volumeMounts: [
							{
								name: 'postgres-data'
								mountPath: '/var/lib/postgresql/data'
							}
						]
					}
				]
				volumes: [
					{
						name: 'postgres-data'
						emptyDir: {}
					}
				]
			}
		}
	}
}

// ------------------------------------------------------------------
// PostgreSQL Service
// ------------------------------------------------------------------
resource postgresService 'core/Service@v1' = {
	metadata: {
		name: postgresName
		namespace: namespace
		labels: {
			app: 'postgres'
			resource: context.resource.name
			'radapp.io/application': context.application == null ? '' : context.application.name
		}
	}
	spec: {
		type: 'ClusterIP'
		selector: {
			app: 'postgres'
			resource: context.resource.name
		}
		ports: [
			{
				protocol: 'TCP'
				port: 5432
				name: 'postgres'
			}
		]
	}
}

output result object = {
	resources: [
		'/planes/kubernetes/local/namespaces/${namespace}/providers/core/Service/${keycloakService.metadata.name}'
		'/planes/kubernetes/local/namespaces/${namespace}/providers/core/Service/${keycloakDiscoveryService.metadata.name}'
		'/planes/kubernetes/local/namespaces/${namespace}/providers/apps/StatefulSet/${keycloak.metadata.name}'
		'/planes/kubernetes/local/namespaces/${namespace}/providers/networking.k8s.io/Ingress/${keycloakIngress.metadata.name}'
		'/planes/kubernetes/local/namespaces/${namespace}/providers/apps/Deployment/${postgres.metadata.name}'
		'/planes/kubernetes/local/namespaces/${namespace}/providers/core/Service/${postgresService.metadata.name}'
	]
	values: {
		issuer: 'http://${effectiveKeycloakPublicHost}/realms/master'
		authEndpoint: 'http://${effectiveKeycloakPublicHost}/realms/master/protocol/openid-connect/auth'
		tokenEndpoint: 'http://${keycloakService.metadata.name}.${namespace}.svc.cluster.local:8080/realms/master/protocol/openid-connect/token'
		userInfoEndpoint: 'http://${keycloakService.metadata.name}.${namespace}.svc.cluster.local:8080/realms/master/protocol/openid-connect/userinfo'
		adminUsername: adminUsername
		postgresHost: '${postgresService.metadata.name}.${namespace}.svc.cluster.local'
		postgresPort: 5432
		database: databaseName
		username: databaseUser
		secrets: {
			#disable-next-line outputs-should-not-contain-secrets
			adminPassword: adminPassword
			#disable-next-line outputs-should-not-contain-secrets
			password: databasePassword
		}
	}
}
