// azure-event-grid.bicep
// Radius Recipe: Radius.Resources/mqttBrokers  (environment: Azure)
//
// Provisions an Azure Event Grid Namespace with MQTT topic spaces enabled.
// The recipe returns host/port/wsPort values that match the mqttBrokers
// resource type contract.
//
// Notes:
// - Event Grid MQTT requires TLS and authenticated clients. Clients must use
//   MQTT v5 and present a Microsoft Entra token through enhanced authentication
//   (Authentication Method `OAUTH2-JWT`), with the CONNECT client identifier set
//   to the object ID of the authenticating principal.
//   https://learn.microsoft.com/azure/event-grid/mqtt-client-microsoft-entra-token-and-rbac
// - Only the `backend` container speaks this dialect. The browser client in
//   `src/frontend/public/index.html` connects to `MQTT_WS_URL` without
//   credentials, so selecting this recipe gives you server-side order
//   processing but no browser-side live streaming.
// - This recipe intentionally focuses on broker endpoint provisioning.
// - Billing warning: `result.resources` is intentionally empty (see below), so
//   Radius does not track the namespace it created. `rad app delete` or a
//   switch to another mqttBrokers recipe leaves the Event Grid namespace
//   running and billing. Delete it manually:
//     az eventgrid namespace delete --name <namespace> --resource-group <rg>

@description('Information about what resource is calling this Recipe. Generated by Radius. For more information visit https://docs.radapp.io/reference/context-schema/')
param context object

@description('Azure region for Event Grid resources.')
param location string = 'eastus'

@description('SKU name for Event Grid Namespace.')
@allowed([
  'Standard'
])
param skuName string = 'Standard'

@description('Namespace capacity in throughput units (1-20).')
@minValue(1)
@maxValue(20)
param capacity int = 1

var namespaceName = 'egns-${uniqueString(context.resource.id)}'

resource eventGridNamespace 'Microsoft.EventGrid/namespaces@2023-12-15-preview' = {
  name: namespaceName
  location: location
  sku: {
    name: skuName
    capacity: capacity
  }
  properties: {
    publicNetworkAccess: 'Enabled'
    topicSpacesConfiguration: {
      state: 'Enabled'
    }
  }
}

output result object = {
  // Keep empty due known Radius Azure scope validation behavior in recipe results.
  resources: []
  values: {
    host: eventGridNamespace.properties.topicSpacesConfiguration.hostname
    // Event Grid MQTT uses secure MQTT on 8883.
    port: 8883
    // Event Grid MQTT over WebSockets uses secure WebSockets on 443.
    wsPort: 443
    protocol: 'mqtts'
    wsProtocol: 'wss'
    authMethod: 'OAUTH2-JWT'
    tokenAudience: 'https://eventgrid.azure.net/'
    resourceId: eventGridNamespace.id
  }
}
