// azure-event-grid.bicep
// Radius Recipe: Radius.Resources/mqttBrokers  (environment: Azure)
//
// Provisions an Azure Event Grid Namespace with MQTT topic spaces enabled.
// The recipe returns host/port/wsPort values that match the mqttBrokers
// resource type contract.
//
// Notes:
// - Event Grid MQTT requires TLS and authenticated clients.
// - This recipe intentionally focuses on broker endpoint provisioning.

@description('Information about what resource is calling this Recipe. Generated by Radius. For more information visit https://docs.radapp.io/reference/context-schema/')
param context object

@description('Azure region for Event Grid resources.')
param location string = 'eastus'

@description('SKU name for Event Grid Namespace.')
@allowed([
  'Standard'
])
param skuName string = 'Standard'

@description('Namespace capacity in throughput units (1-20).')
@minValue(1)
@maxValue(20)
param capacity int = 1

var namespaceName = 'egns-${uniqueString(context.resource.id)}'

resource eventGridNamespace 'Microsoft.EventGrid/namespaces@2023-12-15-preview' = {
  name: namespaceName
  location: location
  sku: {
    name: skuName
    capacity: capacity
  }
  properties: {
    publicNetworkAccess: 'Enabled'
    topicSpacesConfiguration: {
      state: 'Enabled'
    }
  }
}

output result object = {
  // Keep empty due known Radius Azure scope validation behavior in recipe results.
  resources: []
  values: {
    host: eventGridNamespace.properties.topicSpacesConfiguration.hostname
    // Event Grid MQTT uses secure MQTT on 8883.
    port: 8883
    // Event Grid MQTT over WebSockets uses secure WebSockets on 443.
    wsPort: 443
    protocol: 'mqtts'
    wsProtocol: 'wss'
    authMethod: 'OAUTH2-JWT'
    tokenAudience: 'https://eventgrid.azure.net/'
    resourceId: eventGridNamespace.id
  }
}
