// kubernetes-mosquitto.bicep
// Radius Recipe: Radius.Resources/mqttBrokers
//
// Deploys an Eclipse Mosquitto 2 broker on Kubernetes with listener
// configuration that mirrors the docker-compose setup:
//   - Port 1883  : plain MQTT (TCP)
//   - Port 9001  : MQTT over WebSockets

@description('Information about what resource is calling this Recipe. Generated by Radius. For more information visit https://docs.radapp.io/reference/context-schema/')
param context object

@description('TCP port for plain MQTT connections.')
param mqttPort int = 1883

@description('TCP port for MQTT-over-WebSockets connections.')
param wsPort int = 9001

var uniqueName = 'mosquitto-${uniqueString(context.resource.id)}'

extension kubernetes with {
  kubeConfig: ''
  namespace: context.runtime.kubernetes.namespace
} as kubernetes

// ------------------------------------------------------------------
// ConfigMap: mosquitto.conf
// ------------------------------------------------------------------
resource mosquittoConf 'core/ConfigMap@v1' = {
  metadata: {
    name: '${uniqueName}-conf'
    namespace: context.runtime.kubernetes.namespace
    labels: {
      resource: context.resource.name
      'radapp.io/application': context.application == null ? '' : context.application.name
    }
  }
  data: {
    'mosquitto.conf': '''listener 1883
allow_anonymous true
listener 9001
protocol websockets
allow_anonymous true
'''
  }
}

// ------------------------------------------------------------------
// Deployment
// ------------------------------------------------------------------
resource mosquitto 'apps/Deployment@v1' = {
  metadata: {
    name: uniqueName
    namespace: context.runtime.kubernetes.namespace
    labels: {
      app: 'mosquitto'
      resource: context.resource.name
      'radapp.io/application': context.application == null ? '' : context.application.name
    }
  }
  spec: {
    selector: {
      matchLabels: {
        app: 'mosquitto'
        resource: context.resource.name
      }
    }
    template: {
      metadata: {
        labels: {
          app: 'mosquitto'
          resource: context.resource.name
          'radapp.io/application': context.application == null ? '' : context.application.name
        }
      }
      spec: {
        containers: [
          {
            name: 'mosquitto'
            image: 'eclipse-mosquitto:2'
            ports: [
              { containerPort: mqttPort, name: 'mqtt' }
              { containerPort: wsPort,   name: 'mqtt-ws' }
            ]
            volumeMounts: [
              {
                // subPath so we only replace the single file, not the whole dir
                name: 'config'
                mountPath: '/mosquitto/config/mosquitto.conf'
                subPath: 'mosquitto.conf'
                readOnly: true
              }
            ]
          }
        ]
        volumes: [
          {
            name: 'config'
            configMap: {
              name: mosquittoConf.metadata.name
            }
          }
        ]
      }
    }
  }
}

// ------------------------------------------------------------------
// Service: ClusterIP exposing both ports
// ------------------------------------------------------------------
resource svc 'core/Service@v1' = {
  metadata: {
    name: uniqueName
    namespace: context.runtime.kubernetes.namespace
    labels: {
      name: uniqueName
    }
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      app: 'mosquitto'
      resource: context.resource.name
    }
    ports: [
      { port: mqttPort, targetPort: mqttPort, name: 'mqtt' }
      { port: wsPort,   targetPort: wsPort,   name: 'mqtt-ws' }
    ]
  }
}

// ------------------------------------------------------------------
// Recipe result
// ------------------------------------------------------------------
output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${mosquitto.metadata.namespace}/providers/apps/Deployment/${mosquitto.metadata.name}'
    '/planes/kubernetes/local/namespaces/${mosquittoConf.metadata.namespace}/providers/core/ConfigMap/${mosquittoConf.metadata.name}'
  ]
  values: {
    host: '${svc.metadata.name}.${svc.metadata.namespace}.svc.cluster.local'
    port: mqttPort
    wsPort: wsPort
    protocol: 'mqtt'
    wsProtocol: 'ws'
    authMethod: 'none'
    tokenAudience: ''
    resourceId: ''
  }
}
