// azure-postgresql-flexible-server.bicep
// Radius Recipe: Radius.Resources/postgreSqlDatabases
//
// Provisions Azure Database for PostgreSQL Flexible Server and a database.

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Database name.')
param database string = 'trading'

@description('Administrator username.')
param user string = 'tradeadmin'

@secure()
@description('Administrator password.')
#disable-next-line secure-parameter-default
param password string = uniqueString(context.resource.id)

@description('Azure region for PostgreSQL resources. Defaults to the resource group location.')
param location string = resourceGroup().location

@description('Size tier from the portable resource contract.')
@allowed([
  'S'
  'M'
  'L'
])
param size string = 'S'

var serverName = 'pg-${uniqueString(context.resource.id)}'
var skuBySize = {
  S: {
    name: 'Standard_B1ms'
    tier: 'Burstable'
  }
  M: {
    name: 'Standard_B2s'
    tier: 'Burstable'
  }
  L: {
    name: 'Standard_D2s_v3'
    tier: 'GeneralPurpose'
  }
}

resource pg 'Microsoft.DBforPostgreSQL/flexibleServers@2023-12-01-preview' = {
  name: serverName
  location: location
  sku: {
    name: skuBySize[size].name
    tier: skuBySize[size].tier
  }
  properties: {
    administratorLogin: user
    administratorLoginPassword: password
    version: '16'
    storage: {
      storageSizeGB: 32
    }
    backup: {
      backupRetentionDays: 7
      geoRedundantBackup: 'Disabled'
    }
    highAvailability: {
      mode: 'Disabled'
    }
    network: {
      publicNetworkAccess: 'Enabled'
    }
    createMode: 'Default'
  }
}

resource db 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2023-12-01-preview' = {
  parent: pg
  name: database
  properties: {
    charset: 'UTF8'
    collation: 'en_US.utf8'
  }
}

output result object = {
  resources: [
    pg.id
    db.id
  ]
  values: {
    host: pg.properties.fullyQualifiedDomainName
    port: 5432
    database: db.name
    username: user
    secrets: {
      #disable-next-line outputs-should-not-contain-secrets
      password: password
    }
  }
}
