// kubernetes-trading-postgres.bicep
// Radius Recipe: Radius.Resources/postgreSqlDatabases
//
// Deploys a PostgreSQL 16 container on Kubernetes with the portable-apps
// trading schema pre-loaded via an init ConfigMap mounted at
// /docker-entrypoint-initdb.d/init.sql.

@description('Information about what resource is calling this Recipe. Generated by Radius. For more information visit https://docs.radapp.io/reference/context-schema/')
param context object

@description('Name of the PostgreSQL database. Defaults to "trading".')
param database string = 'trading'

@description('PostgreSQL username. Defaults to "trade".')
param user string = 'trade'

@description('PostgreSQL password. Defaults to a unique deterministic value derived from the resource ID.')
@secure()
#disable-next-line secure-parameter-default
param password string = uniqueString(context.resource.id)

@description('Tag for the postgres container image.')
param tag string = '16-alpine'

@description('Memory request sizes per tier.')
var memory = {
  S: { memoryRequest: '512Mi' }
  M: { memoryRequest: '1Gi' }
  L: { memoryRequest: '2Gi' }
}

var sizeKey = context.resource.properties.?size ?? 'S'
var uniqueName = 'postgres-${uniqueString(context.resource.id)}'
var port = 5432

extension kubernetes with {
  kubeConfig: ''
  namespace: context.runtime.kubernetes.namespace
} as kubernetes

// ------------------------------------------------------------------
// ConfigMap: database initialisation SQL (trading schema + seed data)
// ------------------------------------------------------------------
resource initSqlConfigMap 'core/ConfigMap@v1' = {
  metadata: {
    name: '${uniqueName}-init'
    namespace: context.runtime.kubernetes.namespace
    labels: {
      resource: context.resource.name
      'radapp.io/application': context.application == null ? '' : context.application.name
    }
  }
  data: {
    // The SQL is mounted into /docker-entrypoint-initdb.d/ and executed by
    // the official postgres entrypoint on first startup.
    'init.sql': '''
CREATE TABLE IF NOT EXISTS accounts (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  cash_balance NUMERIC(18, 2) NOT NULL DEFAULT 100000.00
);

CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES accounts(id),
  symbol TEXT NOT NULL,
  side TEXT NOT NULL,
  order_type TEXT NOT NULL DEFAULT 'MARKET',
  quantity INTEGER NOT NULL,
  price NUMERIC(18, 2) NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS trades (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id),
  account_id INTEGER NOT NULL REFERENCES accounts(id),
  symbol TEXT NOT NULL,
  side TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  price NUMERIC(18, 2) NOT NULL,
  executed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS positions (
  id SERIAL PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES accounts(id),
  symbol TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  avg_price NUMERIC(18, 2) NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (account_id, symbol)
);

INSERT INTO accounts (name, cash_balance)
VALUES ('Demo Account', 100000.00)
ON CONFLICT DO NOTHING;
'''
  }
}

// ------------------------------------------------------------------
// Deployment
// ------------------------------------------------------------------
resource postgresql 'apps/Deployment@v1' = {
  metadata: {
    name: uniqueName
    namespace: context.runtime.kubernetes.namespace
    labels: {
      app: 'postgresql'
      resource: context.resource.name
      'radapp.io/application': context.application == null ? '' : context.application.name
    }
  }
  spec: {
    selector: {
      matchLabels: {
        app: 'postgresql'
        resource: context.resource.name
      }
    }
    template: {
      metadata: {
        labels: {
          app: 'postgresql'
          resource: context.resource.name
          'radapp.io/application': context.application == null ? '' : context.application.name
        }
      }
      spec: {
        containers: [
          {
            name: 'postgres'
            image: 'postgres:${tag}'
            ports: [
              { containerPort: port }
            ]
            resources: {
              requests: {
                memory: memory[sizeKey].memoryRequest
              }
            }
            env: [
              { name: 'POSTGRES_USER',     value: user }
              { name: 'POSTGRES_PASSWORD', value: password }
              { name: 'POSTGRES_DB',       value: database }
            ]
            volumeMounts: [
              {
                name: 'init-sql'
                mountPath: '/docker-entrypoint-initdb.d'
                readOnly: true
              }
            ]
          }
        ]
        volumes: [
          {
            name: 'init-sql'
            configMap: {
              name: initSqlConfigMap.metadata.name
            }
          }
        ]
      }
    }
  }
}

// ------------------------------------------------------------------
// Service
// ------------------------------------------------------------------
resource svc 'core/Service@v1' = {
  metadata: {
    name: uniqueName
    namespace: context.runtime.kubernetes.namespace
    labels: {
      name: uniqueName
    }
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      app: 'postgresql'
      resource: context.resource.name
    }
    ports: [
      { port: port }
    ]
  }
}

// ------------------------------------------------------------------
// Recipe result: values + secrets consumed by the application
// ------------------------------------------------------------------
output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${postgresql.metadata.namespace}/providers/apps/Deployment/${postgresql.metadata.name}'
    '/planes/kubernetes/local/namespaces/${initSqlConfigMap.metadata.namespace}/providers/core/ConfigMap/${initSqlConfigMap.metadata.name}'
  ]
  values: {
    host: '${svc.metadata.name}.${svc.metadata.namespace}.svc.cluster.local'
    port: port
    database: database
    username: user
    secrets: {
      #disable-next-line outputs-should-not-contain-secrets
      password: password
    }
  }
}
