apiVersion: v2
name: min
description: Min capability portfolio chart for Adaptive Apps.
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - adaptive-apps
  - capability-portfolio
  - min
home: https://github.com/microsoft/adaptive-apps
sources:
  - https://github.com/microsoft/adaptive-apps
maintainers:
  - name: adaptive-apps
