// azure-workload-identity.bicep
// Radius Recipe: Radius.Resources/workloadIdentities (AKS + Azure)
//
// Pass-through recipe: accepts a pre-provisioned managed identity (created by
// app-wi-setup.sh) and surfaces its values as structured outputs for the app model.
//
// Managed identity, federated credential, and RBAC must be provisioned before
// deploying the app — use tutorials/min-getting-started/deploy-to-azure/app-wi-setup.sh.

@description('Information about what resource is calling this Recipe. Generated by Radius. For more information visit https://docs.radapp.io/reference/context-schema/')
param context object

@description('Client ID of the pre-provisioned user-assigned managed identity.')
param clientId string = ''

@description('Kubernetes service account name bound to this workload identity.')
param serviceAccountName string = 'default'

var namespace = string(context.runtime.?kubernetes.?namespace ?? 'default')
var tokenAudience = 'https://eventgrid.azure.net/'

output result object = {
  resources: []
  values: {
    clientId: clientId
    principalId: ''
    tenantId: subscription().tenantId
    serviceAccountNamespace: namespace
    boundServiceAccountName: serviceAccountName
    authMethod: 'OAUTH2-JWT'
    tokenAudience: tokenAudience
  }
}
