// azure-workload-identity.bicep
// Radius Recipe: Radius.Resources/workloadIdentities (AKS + Azure)
//
// Provisions a user-assigned managed identity and optionally configures:
// - federated identity credential for AKS OIDC workload identity
// - Kubernetes service account annotation for azure.workload.identity/client-id
// - Event Grid TopicSpaces RBAC assignment(s)

@description('Information about what resource is calling this Recipe. Generated by Radius. For more information visit https://docs.radapp.io/reference/context-schema/')
param context object

@description('Kubernetes service account to bind workload identity to.')
param serviceAccountName string = 'default'

@description('Whether to create/update the Kubernetes service account with workload identity annotation. Azure recipe currently treats this as informational and does not mutate Kubernetes resources.')
param createServiceAccount bool = true

@description('AKS OIDC issuer URL (for example: https://eastus.oic.prod-aks.azure.com/<tenant>/<guid>/).')
param oidcIssuer string = ''

var namespace = string(context.runtime.?kubernetes.?namespace ?? 'default')
var identityName = 'wi-${uniqueString(context.resource.id)}'
var subject = 'system:serviceaccount:${namespace}:${serviceAccountName}'
var tokenAudience = 'https://eventgrid.azure.net/'

resource workloadIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: identityName
  location: resourceGroup().location
}

resource federatedCredential 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2023-01-31' = if (!empty(oidcIssuer)) {
  name: 'aks-wi'
  parent: workloadIdentity
  properties: {
    issuer: oidcIssuer
    subject: subject
    audiences: [
      'api://AzureADTokenExchange'
    ]
  }
}

// NOTE: Microsoft.Authorization/roleAssignments are provisioned outside this recipe
// (az role assignment create) due to Radius bicep-de not supporting the
// Microsoft.Authorization ARM namespace in recipe deployments.

output result object = {
  resources: [workloadIdentity.id]
  values: {
    clientId: workloadIdentity.properties.clientId
    principalId: workloadIdentity.properties.principalId
    tenantId: ''
    serviceAccountNamespace: namespace
    boundServiceAccountName: createServiceAccount ? serviceAccountName : serviceAccountName
    authMethod: 'OAUTH2-JWT'
    tokenAudience: tokenAudience
  }
}
