// local-noop.bicep
// Radius Recipe: Radius.Resources/workloadIdentities (local Kubernetes)
//
// Local environments don't need Azure federated workload identity.
// This recipe returns a compatible output contract with empty identity values.

@description('Information about what resource is calling this Recipe. Generated by Radius. For more information visit https://docs.radapp.io/reference/context-schema/')
param context object

@description('Kubernetes service account name for app workload. For local env this is informational only.')
param serviceAccountName string = 'default'

output result object = {
  resources: []
  values: {
    clientId: ''
    principalId: ''
    tenantId: ''
    serviceAccountNamespace: context.runtime.kubernetes.namespace
    boundServiceAccountName: serviceAccountName
    authMethod: 'none'
    tokenAudience: ''
  }
}
