// azure-openai.bicep
// Radius Recipe: Radius.Resources/aiAgents  (environment: Azure)
//
// Creates an Azure OpenAI account and a model deployment.
// The provisioned endpoint is OpenAI-SDK-compatible when used with an API key,
// so the ai-agent runs with AI_PROVIDER=openai and the generated key.
//
// Prerequisites:
//   - Radius Environment configured with an Azure scope (resource group + subscription)
//   - Microsoft.CognitiveServices resource provider registered in the subscription
//
// This recipe outputs:
//   provider = "openai"   (ai-agent uses OpenAI SDK with an API key against an Azure endpoint)
//   endpoint  = https://<account>.openai.azure.com/
//   apiKey    = <account key 1>  (stored as a Radius secret)

@description('Information about what resource is calling this Recipe. Generated by Radius. For more information visit https://docs.radapp.io/reference/context-schema/')
param context object

@description('Azure region for the Cognitive Services account.')
param location string = 'eastus'

@description('Model name to deploy. Defaults to the model property on the resource, or gpt-4o.')
param model string = context.resource.properties.?model ?? 'gpt-4o'

@description('Token capacity in thousands of tokens per minute (TPM) for the deployment.')
param capacityK int = 10

var accountName = 'aoai-${uniqueString(context.resource.id)}'

// ------------------------------------------------------------------
// Azure OpenAI account  (kind = OpenAI under Cognitive Services)
// ------------------------------------------------------------------
resource openAIAccount 'Microsoft.CognitiveServices/accounts@2024-10-01' = {
  name: accountName
  location: location
  kind: 'OpenAI'
  sku: {
    name: 'S0'
  }
  properties: {
    customSubDomainName: accountName
    publicNetworkAccess: 'Enabled'
  }
}

// ------------------------------------------------------------------
// Model deployment — reuses the model name as the deployment name so
// the OpenAI SDK can address it without a separate deployment alias.
// ------------------------------------------------------------------
resource modelDeployment 'Microsoft.CognitiveServices/accounts/deployments@2024-10-01' = {
  parent: openAIAccount
  name: model
  sku: {
    name: 'GlobalStandard'
    capacity: capacityK
  }
  properties: {
    model: {
      format: 'OpenAI'
      name: model
    }
  }
}

// ------------------------------------------------------------------
// Recipe result
// ------------------------------------------------------------------
output result object = {
  // Note: ARM resource IDs are intentionally omitted from the resources array.
  // Radius v0.52 incorrectly validates these against the Radius group scope
  // rather than the Azure provider scope configured on the environment.
  resources: []
  values: {
    // provider="azure-key" tells the ai-agent to use AzureOpenAIClient with an API key.
    // This ensures the correct Azure OpenAI API path format is used.
    provider: 'azure-key'
    endpoint: openAIAccount.properties.endpoint
    model: model
    secrets: {
      #disable-next-line outputs-should-not-contain-secrets
      apiKey: openAIAccount.listKeys().key1
    }
  }
}
