// kubernetes-kaito.bicep
// Radius Recipe: Radius.Resources/aiModels  (environment: local Kubernetes with Kaito)
//
// Deploys an open-source LLM inference server on Kubernetes using the Kaito operator
// in "bring your own GPU" (BYO) mode — node auto-provisioning is disabled.
// The Kaito operator:
//   1. Selects an existing GPU node via labelSelector (nvidia.com/gpu=true)
//   2. Downloads the model specified by `preset`
//   3. Exposes an OpenAI-compatible HTTP endpoint as a ClusterIP Service named
//      workspace-<workspaceName>, accessible at:
//      http://workspace-<workspaceName>.<namespace>.svc.cluster.local:80/v1
//
// Prerequisites on the cluster:
//   - k3s (or any Kubernetes distro) with the Kaito operator installed
//     (helm install kaito … --set nodeAutoProvisioning.enabled=false)
//   - A single GPU node labeled:  nvidia.com/gpu=true
//   - NVIDIA device plugin / GPU operator installed
//
// WSL2 / k3s: Kaito does NOT set runtimeClassName on the created StatefulSet,
// and it will revert any manual patch on reconciliation.
// The recommended fix is to make nvidia the default containerd runtime in k3s:
//   1. sudo cp /var/lib/rancher/k3s/agent/etc/containerd/config.toml \
//              /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl
//   2. Add [plugins.'io.containerd.cri.v1.runtime'.containerd]
//        default_runtime_name = "nvidia"
//      before the runtimes.runc section in config.toml.tmpl
//   3. sudo systemctl restart k3s
// IMPORTANT: config.toml.tmpl replaces the entire config — always start from
// the full generated config.toml, not an empty file.
// See the root README for the full instructions.
//
// Supported model presets (see https://github.com/kaito-project/kaito for the full list):
//   phi-3-mini, mistral-7b, llama-3.1-8b-instruct, falcon-7b, …
//
// This recipe outputs:
//   provider = "local"  (ai-agent should use the OpenAI SDK against a local endpoint)
//   endpoint = http://workspace-<name>.<ns>.svc.cluster.local:80/v1
//   apiKey   = ""       (Kaito endpoints do not require authentication)

@description('Information about what resource is calling this Recipe. Generated by Radius. For more information visit https://docs.radapp.io/reference/context-schema/')
param context object

@description('Kaito model preset name (see https://github.com/kaito-project/kaito/blob/main/presets/workspace/models/supported_models.yaml). Defaults to the model property on the resource, or qwen2.5-coder-7b-instruct.')
param preset string = context.resource.properties.?model ?? 'qwen2.5-coder-7b-instruct'

@description('Label key used to select the existing GPU node (BYO GPU mode — no auto-provisioning).')
param gpuNodeLabelKey string = 'nvidia.com/gpu'

@description('Label value for the GPU node selector.')
param gpuNodeLabelValue string = 'true'

var workspaceName = 'trading-ai-${uniqueString(context.resource.id)}'
var configMapName = '${workspaceName}-inference-params'
// Kaito v0.9.0 creates a ClusterIP Service with the same name as the Workspace (no "workspace-" prefix)
var kaitoServiceName = workspaceName
var inferenceEndpoint = 'http://${kaitoServiceName}.${context.runtime.kubernetes.namespace}.svc.cluster.local:80/v1'

extension kubernetes with {
  kubeConfig: ''
  namespace: context.runtime.kubernetes.namespace
} as kubernetes

// ------------------------------------------------------------------
// ConfigMap with vLLM inference parameters.
// Kaito reads the inference_config.yaml key from this ConfigMap.
// See https://kaito-project.github.io/kaito/docs/inference/#inference-with-custom-parameters
// ------------------------------------------------------------------
resource inferenceConfig 'core/ConfigMap@v1' = {
  metadata: {
    name: configMapName
    namespace: context.runtime.kubernetes.namespace
  }
  data: {
    'inference_config.yaml': '''vllm:
  max-model-len: 2048
  gpu-memory-utilization: 0.75
  enforce-eager: true
'''
  }
}

// ------------------------------------------------------------------
// Kaito Workspace CR — BYO GPU mode (disableNodeAutoProvisioning=true).
// The Kaito operator watches this resource, selects the existing GPU node
// via labelSelector, pulls the model, and starts the inference server.
// The operator also creates the ClusterIP Service workspace-<workspaceName>.
// ------------------------------------------------------------------
resource kaitoWorkspace 'kaito.sh/Workspace@v1beta1' = {
  metadata: {
    name: workspaceName
    namespace: context.runtime.kubernetes.namespace
    labels: {
      resource: context.resource.name
      'radapp.io/application': context.application == null ? '' : context.application.name
    }
  }
  resource: {
    labelSelector: {
      matchLabels: {
        '${gpuNodeLabelKey}': gpuNodeLabelValue
      }
    }
  }
  inference: {
    preset: {
      name: preset
    }
    config: inferenceConfig.metadata.name
  }
}

// Kaito preset names are already the lowercase model identifier vLLM serves under
// (e.g. preset 'qwen2.5-coder-7b-instruct' is served as model 'qwen2.5-coder-7b-instruct').
var vllmModelName = toLower(preset)

// ------------------------------------------------------------------
// Recipe result
// ------------------------------------------------------------------
output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${context.runtime.kubernetes.namespace}/providers/kaito.sh/Workspace/${workspaceName}'
    '/planes/kubernetes/local/namespaces/${context.runtime.kubernetes.namespace}/providers/core/ConfigMap/${configMapName}'
  ]
  values: {
    // provider="local" tells the ai-agent to use the OpenAI SDK pointed at the local endpoint
    provider: 'local'
    endpoint: inferenceEndpoint
    model: vllmModelName
    secrets: {
      // Kaito endpoints do not require an API key
      #disable-next-line outputs-should-not-contain-secrets
      apiKey: ''
    }
  }
}
