{{- if .Values.components.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "computeCore.keycloak.serviceName" . }}-admin
  labels:
    {{- include "computeCore.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
type: Opaque
stringData:
  username: {{ .Values.keycloak.admin.username | quote }}
  password: {{ .Values.keycloak.admin.password | quote }}
{{- end }}
