{{- if and .Values.components.keycloak.enabled .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "computeCore.keycloak.postgresqlName" . }}-auth
  labels:
    {{- include "computeCore.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
type: Opaque
stringData:
  database: {{ .Values.postgresql.auth.database | quote }}
  username: {{ .Values.postgresql.auth.username | quote }}
  password: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
