{{- if and .Values.components.keycloak.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "computeCore.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "computeCore.labels" . | nindent 4 }}
{{- end }}
